name:                random-dot-org
version:             0.1.0.0
github:              "mpilgrem/random-dot-org"
license:             BSD3
author:              "Mike Pilgrem"
maintainer:          "public@pilgrem.com"
copyright:           "Copyright 2022 Mike Pilgrem"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Haskell bindings to random.org Basic API (Release 4)
category:            Test

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mpilgrem/random-dot-org#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- http-client
- http-client-tls
- servant
- servant-client
- servant-jsonrpc
- servant-jsonrpc-client
- time
- uuid-types

ghc-options:
- -Wall

flags:
  example:
    description: Build the example application random-dot-org-example.
    manual: true
    default: false

library:
  source-dirs: src

executables:
  random-dot-org-example:
    main:                Main.hs
    source-dirs:         example
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - random-dot-org
    when:
    - condition: "!flag(example)"
      buildable: false
